### PR TITLE
#28 Update story data structure

### PR DESCRIPTION
**Pull request by lekowan**
I've revisited the story data structure.
I've removed the keys we won't need when using chatGPT generated content.
I've also merged the dictionary with the story data as I think it will be more manageable. 

I just need to refine the logic for breaking down sentences into words that can be looked up. Currently it relies on sentences that have spaces and no punctuation. I'll do this in a separate ticket.

I think we need to think about how to add the image references for each speaker in the dialogue.
I've added a speakerGender key as I think this will be useful when using speechSynthesis.

### CODE REVIEW

**Review by seanmturley — COMMENTED** [review]
The data structure changes look sensible. Having the dictionary collocated with the story seems a big improvement in managing the data.

The changes are more than I can get through tonight. If you want to go ahead an merge them that's fine. If they're not merged tomorrow morning, I'll look at them in more detail.

**Comment by lekowan** [comment]
Do you have any views on how we could store the speaker images and the thumbnail for each story?
I think once we have that in place, we can start adding content, see what it looks like and start testing.

**Comment by lekowan** [comment]
I've fixed the conflicts with master. If you're happy with this PR, you can merge ir.

**Comment by lekowan** [comment]
I had forgotten how the avator component looked! It's actually really simple to pull images from the public > avatars !

**Pull request merged**
